In [12]:
from utils.tlc_loader import *
from utils.schema_explorer import *

In [13]:
yellow_taxi_january_2013 = TLCLoader.load_taxi("yellow", 2013, 1)
yellow_taxi_january_2014 = TLCLoader.load_taxi("yellow", 2014, 1)
yellow_taxi_january_2015 = TLCLoader.load_taxi("yellow", 2015, 1)
yellow_taxi_january_2016 = TLCLoader.load_taxi("yellow", 2016, 1)
yellow_taxi_january_2017 = TLCLoader.load_taxi("yellow", 2017, 1)
yellow_taxi_january_2018 = TLCLoader.load_taxi("yellow", 2018, 1)
yellow_taxi_january_2019 = TLCLoader.load_taxi("yellow", 2019, 1)
yellow_taxi_january_2020 = TLCLoader.load_taxi("yellow", 2020, 1)
yellow_taxi_january_2021 = TLCLoader.load_taxi("yellow", 2021, 1)
yellow_taxi_january_2022 = TLCLoader.load_taxi("yellow", 2022, 1)
yellow_taxi_january_2023 = TLCLoader.load_taxi("yellow", 2023, 1)

green_taxi_january_2014 = TLCLoader.load_taxi("green", 2014, 1)
green_taxi_january_2015 = TLCLoader.load_taxi("green", 2015, 1)
green_taxi_january_2016 = TLCLoader.load_taxi("green", 2016, 1)
green_taxi_january_2017 = TLCLoader.load_taxi("green", 2017, 1)
green_taxi_january_2018 = TLCLoader.load_taxi("green", 2018, 1)
green_taxi_january_2019 = TLCLoader.load_taxi("green", 2019, 1)
green_taxi_january_2020 = TLCLoader.load_taxi("green", 2020, 1)
green_taxi_january_2021 = TLCLoader.load_taxi("green", 2021, 1)
green_taxi_january_2022 = TLCLoader.load_taxi("green", 2022, 1)
green_taxi_january_2023 = TLCLoader.load_taxi("green", 2023, 1)

zones = TLCLoader.load_zones()

In [14]:
yellow_dfs = {
    "2013": yellow_taxi_january_2013,
    "2014": yellow_taxi_january_2014,
    "2015": yellow_taxi_january_2015,
    "2016": yellow_taxi_january_2016,
    "2017": yellow_taxi_january_2017,
    "2018": yellow_taxi_january_2018,
    "2019": yellow_taxi_january_2019,
    "2020": yellow_taxi_january_2020,
    "2021": yellow_taxi_january_2021,
    "2022": yellow_taxi_january_2022,
    "2023": yellow_taxi_january_2023,
}

In [15]:
SchemaExplorer.compare_columns(yellow_dfs)

,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
DOLocationID,True,True,True,True,True,True,True,True,True,True,True
PULocationID,True,True,True,True,True,True,True,True,True,True,True
RatecodeID,True,True,True,True,True,True,True,True,True,True,True
VendorID,True,True,True,True,True,True,True,True,True,True,True
airport_fee,True,True,True,True,True,True,True,True,True,True,True
congestion_surcharge,True,True,True,True,True,True,True,True,True,True,True
extra,True,True,True,True,True,True,True,True,True,True,True
fare_amount,True,True,True,True,True,True,True,True,True,True,True
improvement_surcharge,True,True,True,True,True,True,True,True,True,True,True
mta_tax,True,True,True,True,True,True,True,True,True,True,True
passenger_count,True,True,True,True,True,True,True,True,True,True,True
payment_type,True,True,True,True,True,True,True,True,True,True,True
store_and_fwd_flag,True,True,True,True,True,True,True,True,True,True,True
tip_amount,True,True,True,True,True,True,True,True,True,True,True
tolls_amount,True,True,True,True,True,True,True,True,True,True,True
total_amount,True,True,True,True,True,True,True,True,True,True,True
tpep_dropoff_datetime,True,True,True,True,True,True,True,True,True,True,True
tpep_pickup_datetime,True,True,True,True,True,True,True,True,True,True,True
trip_distance,True,True,True,True,True,True,True,True,True,True,True

In [16]:
SchemaExplorer.compare_dtypes(yellow_dfs)

,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
column,,,,,,,,,,,
DOLocationID,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64
PULocationID,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64
RatecodeID,int64,int64,int64,int64,int64,int64,float64,float64,float64,float64,float64
VendorID,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64
airport_fee,object,object,object,object,object,float64,object,object,float64,float64,float64
congestion_surcharge,object,float64,object,object,object,float64,float64,float64,float64,float64,float64
extra,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
fare_amount,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
improvement_surcharge,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
mta_tax,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
passenger_count,int64,int64,int64,int64,int64,int64,float64,float64,float64,float64,float64
payment_type,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64
store_and_fwd_flag,str,str,str,str,str,str,str,str,str,str,str
tip_amount,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
tolls_amount,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
total_amount,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
tpep_dropoff_datetime,datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us]
tpep_pickup_datetime,datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us]
trip_distance,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64

In [17]:
SchemaExplorer.show_schema_differences(yellow_dfs)

,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
column,,,,,,,,,,,
RatecodeID,int64,int64,int64,int64,int64,int64,float64,float64,float64,float64,float64
airport_fee,object,object,object,object,object,float64,object,object,float64,float64,float64
congestion_surcharge,object,float64,object,object,object,float64,float64,float64,float64,float64,float64
passenger_count,int64,int64,int64,int64,int64,int64,float64,float64,float64,float64,float64

In [18]:
green_dfs = {
    "2014": green_taxi_january_2014,
    "2015": green_taxi_january_2015,
    "2016": green_taxi_january_2016,
    "2017": green_taxi_january_2017,
    "2018": green_taxi_january_2018,
    "2019": green_taxi_january_2019,
    "2020": green_taxi_january_2020,
    "2021": green_taxi_january_2021,
    "2022": green_taxi_january_2022,
    "2023": green_taxi_january_2023,
}

In [19]:
SchemaExplorer.compare_columns(green_dfs)

,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
DOLocationID,True,True,True,True,True,True,True,True,True,True
PULocationID,True,True,True,True,True,True,True,True,True,True
RatecodeID,True,True,True,True,True,True,True,True,True,True
VendorID,True,True,True,True,True,True,True,True,True,True
congestion_surcharge,True,True,True,True,True,True,True,True,True,True
ehail_fee,True,True,True,True,True,True,True,True,True,True
extra,True,True,True,True,True,True,True,True,True,True
fare_amount,True,True,True,True,True,True,True,True,True,True
improvement_surcharge,True,True,True,True,True,True,True,True,True,True
lpep_dropoff_datetime,True,True,True,True,True,True,True,True,True,True
lpep_pickup_datetime,True,True,True,True,True,True,True,True,True,True
mta_tax,True,True,True,True,True,True,True,True,True,True
passenger_count,True,True,True,True,True,True,True,True,True,True
payment_type,True,True,True,True,True,True,True,True,True,True
store_and_fwd_flag,True,True,True,True,True,True,True,True,True,True
tip_amount,True,True,True,True,True,True,True,True,True,True
tolls_amount,True,True,True,True,True,True,True,True,True,True
total_amount,True,True,True,True,True,True,True,True,True,True
trip_distance,True,True,True,True,True,True,True,True,True,True
trip_type,True,True,True,True,True,True,True,True,True,True

In [20]:
SchemaExplorer.compare_dtypes(green_dfs)

,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
column,,,,,,,,,,
DOLocationID,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64
PULocationID,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64
RatecodeID,int64,int64,int64,int64,int64,float64,float64,float64,float64,float64
VendorID,int64,int64,int64,int64,int64,int64,int64,int64,int64,int64
congestion_surcharge,object,object,float64,object,object,float64,float64,float64,float64,float64
ehail_fee,object,object,object,object,object,float64,object,object,object,object
extra,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
fare_amount,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
improvement_surcharge,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
lpep_dropoff_datetime,datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us]
lpep_pickup_datetime,datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us],datetime64[us]
mta_tax,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
passenger_count,int64,int64,int64,int64,int64,float64,float64,float64,float64,float64
payment_type,int64,int64,int64,int64,int64,float64,float64,float64,float64,float64
store_and_fwd_flag,str,str,str,str,str,str,str,str,str,str
tip_amount,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
tolls_amount,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
total_amount,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
trip_distance,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
trip_type,float64,float64,float64,int64,float64,float64,float64,float64,float64,float64

In [21]:
SchemaExplorer.show_schema_differences(green_dfs)

,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
column,,,,,,,,,,
RatecodeID,int64,int64,int64,int64,int64,float64,float64,float64,float64,float64
congestion_surcharge,object,object,float64,object,object,float64,float64,float64,float64,float64
ehail_fee,object,object,object,object,object,float64,object,object,object,object
passenger_count,int64,int64,int64,int64,int64,float64,float64,float64,float64,float64
payment_type,int64,int64,int64,int64,int64,float64,float64,float64,float64,float64
trip_type,float64,float64,float64,int64,float64,float64,float64,float64,float64,float64